service: kamal-example

servers:
  web:
    labels:
      traefik.http.routers.kamal-example-web-production.rule: Host(`kamal-example.cklos.com`)
      traefik.http.routers.kamal-example-web_secure-production.entrypoints: websecure
      traefik.http.routers.kamal-example-web_secure-production.rule: Host(`kamal-example.cklos.com`)
      traefik.http.routers.kamal-example-web_secure-production.tls.certresolver: letsencrypt

env:
  clear:
    HOSTNAME: kamal-example.cklos.com
    DB_HOST: kamal-example-db  # hostname: cklos-kamal-1

volumes:
  - "/storage:/rails/storage"

accessories:
  db:
    image: postgres:15
    host: 95.216.199.204  # hostname: cklos-kamal-1
    options:
      network: "kamal"
    env:
      clear:
        POSTGRES_USER: "kamal_example"
        POSTGRES_DB: 'kamal_example_production'
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.2
    host: 95.216.199.204  # hostname: cklos-kamal-1
    options:
      network: "kamal"
    cmd: "redis-server --requirepass <%= File.read(File.expand_path('.redis-password.production', __dir__)) %>"
    directories:
      - data:/data
