service: staging-kamal-example
image: kasku/kamal-example

servers:
  web:
    hosts:
      - 95.217.191.137
      - 95.217.160.21
    labels:
      traefik.http.routers.cklos-staging.rule: Host(`staging2.kamal-example.cklos.com`)
      traefik.http.routers.cklos-staging_secure.entrypoints: websecure
      traefik.http.routers.cklos-staging_secure.rule: Host(`staging2.kamal-example.cklos.com`)
      traefik.http.routers.cklos-staging_secure.tls: true
      traefik.http.routers.cklos-staging_secure.tls.certresolver: letsencrypt

  worker:
    hosts:
      - 95.217.191.137
      - 95.217.160.21
    cmd: bundle exec sidekiq

env:
  clear:
    HOSTNAME: staging2.kamal-example.cklos.com
    DB_HOST: 10.0.0.3
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - KAMAL_REGISTRY_PASSWORD
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - REDIS_URL

volumes:
  - "/storage-staging:/rails/storage"

registry:
  username: kasku
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: webapp

builder:
  multiarch: false

accessories:
  db:
    image: postgres:15
    host: 95.217.191.137
    port: 5432
    env:
      clear:
        POSTGRES_USER: "kamal_example"
        POSTGRES_DB: 'kamal_example_production'
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql.staging:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data-staging:/var/lib/postgresql/data

  redis:
    image: redis:7.2.2
    host: 95.217.160.21
    port: 6379
    cmd: "redis-server --requirepass <%= File.read(File.expand_path('.redis-password.staging', __dir__)) %>"
    directories:
      - data-staging:/data
